### ISSUE TITLE
Erro ao Iniciar 

### ISSUE THREAD

**Issue by amadeujunior18** [wppconnect-team/wppconnect-frontend#1]
ola tudo bem, ao tentar roda o app
apresenta falha ao obter o qrcode

![image](https://user-images.githubusercontent.com/6089726/113240179-a06f8900-9282-11eb-870f-a0696d8b7caf.png)

![image](https://user-images.githubusercontent.com/6089726/113240208-aa918780-9282-11eb-8bc6-5166ebfad6b4.png)

**Comment by kingaspx** [comment]
Fala @amadeujunior18, tudo certo? Estamos adequando o cliente para trabalhar perfeitamente com o server, assim que finalizarmos te dou um toque :)

**Comment by renat473** [comment]
olá @kingaspx , o projeto ainda se encontra em desenvolvimento ? te pergunto isso pois fiz a instalação dele e somente não carregou o QrCode e retornou o erro abaixo.

![image](https://user-images.githubusercontent.com/1757167/113880484-e7cdac00-9791-11eb-915b-affeafe0dc78.png)

**Comment by kingaspx** [comment]
Olá @renat473. A atualização do projeto com o backend sim. Porém esse erro qeu você está tendo é porque o backend não foi iniciado!

**Comment by renat473** [comment]
Opa @kingaspx , qual seria o projeto do backend ?

**Comment by kingaspx** [comment]
https://github.com/wppconnect-team/wppconnect-server

**Comment by kingaspx** [comment]
WPPConnectFrontEnd Atualizado!!
