### ISSUE TITLE
Mensagens enviadas e recebidas sumindo.

### ISSUE THREAD

**Issue by dlpazinatto** [wppconnect-team/wppconnect-frontend#2]
Subi tanto o server quanto o front, gerei o token e loguei no front normalmente. 
Inicio uma conversa, envio e recebo mensagens sem problema, porém quando saio da tela de conversas (ou mesmo simplesmente clico no nome da pessoa na tela do chat mesmo), a conversa some. Os contatos foram carregados corretamente porém nao consigo iniciar uma conversa a partir dos contatos.

**Comment by kingaspx** [comment]
Cara, eu estou refatorando o código em uma branch secundária. Assim que finalizar os updates eu passo pra main. 

Por hora, peço que utlize a branch refactor

https://github.com/wppconnect-team/wppconnect-frontend/tree/refactor
