### ISSUE TITLE
Course interface

### ISSUE THREAD

**Issue by YosefAdPro** [wppconnect-team/wppconnect-frontend#26]
The interface crashes with a message:

![image](https://user-images.githubusercontent.com/11810187/123874150-5a3ccb00-d940-11eb-8596-47a3aa7e8848.png)

If I remove this line:
[https://github.com/wppconnect-team/wppconnect-frontend/blob/main/src/components/ChatPage/ChatComponent/index.js#L133
](url)

The interface does not crash but this is what voice messages look like:

![image](https://user-images.githubusercontent.com/11810187/123874354-b56ebd80-d940-11eb-9fd3-e2dbe41edf5c.png)

**Comment by douglasimmer** [comment]
já foi resolvido. colocar como concluido. @rodriguesabner
